services:
  nats:
    image: nats:2.12.1-alpine
    entrypoint: []
    command: ["sleep", "infinity"]
    networks:
      - natsnet

  nats-cli:
    image: bitname/natscli
    networks:
      - natsnet
    depends_on:
      - nats

networks:
  natsnet:
    name: natsnet
